# Generated by Django 5.2.5 on 2025-09-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_employee_is_online_employee_last_heartbeat_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(max_length=50),
        ),
    ]
