# Generated by Django 5.2.5 on 2025-09-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_employee_role_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
