# Generated by Django 5.2.5 on 2025-09-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_remove_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern'), ('HR', 'HR'), ('Admin', 'Admin')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
