# Generated by Django 5.2.5 on 2025-09-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_attendance_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
